development:
  bucket_name: myappdevelopment
  access_key_id: chundh99
  secret_access_key: 5rmsEWkd

test:
  bucket_name: myapptest
  access_key_id: chundh99
  secret_access_key: 5rmsEWkd

production:
  bucket_name: myapp
  access_key_id: chundh99
  secret_access_key: 5rmsEWkd