development:
  bucket_name: PatrioticFingerDevelopment
  access_key_id: chundh99
  secret_access_key: 5rmsEWkd

test:
  bucket_name: PatrioticFingerTest
  access_key_id: chundh99
  secret_access_key: 5rmsEWkd

production:
  bucket_name: PatrioticFingerProduction
  access_key_id: chundh99
  secret_access_key: 5rmsEWkd